/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6eGSV1Wwq98
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from '~/components/ui/select';
import { Button } from '~/components/ui/button';

export function ProductList() {
  return (
    <section className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 p-4 md:p-6">
      <div className="bg-white rounded-lg shadow-md overflow-hidden dark:bg-gray-950">
        <img
          alt="Product 1"
          className="w-full h-48 object-cover"
          height="200"
          src="/placeholder.svg"
          style={{
            aspectRatio: '300/200',
            objectFit: 'cover',
          }}
          width="300"
        />
        <div className="p-4 grid gap-4">
          <div>
            <h3 className="text-lg font-semibold">Stylish T-Shirt</h3>
            <p className="text-gray-500 dark:text-gray-400 text-sm">$29.99</p>
          </div>
          <div className="flex items-center gap-2">
            <Select className="w-24" defaultValue="1">
              <SelectTrigger>
                <SelectValue placeholder="Qty" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="1">1</SelectItem>
                <SelectItem value="2">2</SelectItem>
                <SelectItem value="3">3</SelectItem>
                <SelectItem value="4">4</SelectItem>
                <SelectItem value="5">5</SelectItem>
              </SelectContent>
            </Select>
            <Button className="flex-1" size="sm">
              Add to cart
            </Button>
          </div>
        </div>
      </div>
      <div className="bg-white rounded-lg shadow-md overflow-hidden dark:bg-gray-950">
        <img
          alt="Product 2"
          className="w-full h-48 object-cover"
          height="200"
          src="/placeholder.svg"
          style={{
            aspectRatio: '300/200',
            objectFit: 'cover',
          }}
          width="300"
        />
        <div className="p-4 grid gap-4">
          <div>
            <h3 className="text-lg font-semibold">Comfortable Jeans</h3>
            <p className="text-gray-500 dark:text-gray-400 text-sm">$49.99</p>
          </div>
          <div className="flex items-center gap-2">
            <Select className="w-24" defaultValue="1">
              <SelectTrigger>
                <SelectValue placeholder="Qty" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="1">1</SelectItem>
                <SelectItem value="2">2</SelectItem>
                <SelectItem value="3">3</SelectItem>
                <SelectItem value="4">4</SelectItem>
                <SelectItem value="5">5</SelectItem>
              </SelectContent>
            </Select>
            <Button className="flex-1" size="sm">
              Add to cart
            </Button>
          </div>
        </div>
      </div>
      <div className="bg-white rounded-lg shadow-md overflow-hidden dark:bg-gray-950">
        <img
          alt="Product 3"
          className="w-full h-48 object-cover"
          height="200"
          src="/placeholder.svg"
          style={{
            aspectRatio: '300/200',
            objectFit: 'cover',
          }}
          width="300"
        />
        <div className="p-4 grid gap-4">
          <div>
            <h3 className="text-lg font-semibold">Elegant Dress</h3>
            <p className="text-gray-500 dark:text-gray-400 text-sm">$79.99</p>
          </div>
          <div className="flex items-center gap-2">
            <Select className="w-24" defaultValue="1">
              <SelectTrigger>
                <SelectValue placeholder="Qty" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="1">1</SelectItem>
                <SelectItem value="2">2</SelectItem>
                <SelectItem value="3">3</SelectItem>
                <SelectItem value="4">4</SelectItem>
                <SelectItem value="5">5</SelectItem>
              </SelectContent>
            </Select>
            <Button className="flex-1" size="sm">
              Add to cart
            </Button>
          </div>
        </div>
      </div>
      <div className="bg-white rounded-lg shadow-md overflow-hidden dark:bg-gray-950">
        <img
          alt="Product 4"
          className="w-full h-48 object-cover"
          height="200"
          src="/placeholder.svg"
          style={{
            aspectRatio: '300/200',
            objectFit: 'cover',
          }}
          width="300"
        />
        <div className="p-4 grid gap-4">
          <div>
            <h3 className="text-lg font-semibold">Cozy Sweater</h3>
            <p className="text-gray-500 dark:text-gray-400 text-sm">$39.99</p>
          </div>
          <div className="flex items-center gap-2">
            <Select className="w-24" defaultValue="1">
              <SelectTrigger>
                <SelectValue placeholder="Qty" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="1">1</SelectItem>
                <SelectItem value="2">2</SelectItem>
                <SelectItem value="3">3</SelectItem>
                <SelectItem value="4">4</SelectItem>
                <SelectItem value="5">5</SelectItem>
              </SelectContent>
            </Select>
            <Button className="flex-1" size="sm">
              Add to cart
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
}
